### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by DrPaprikaa**
Made the Readme more user-friendly
Added badges
Added contributors list
I suggest putting the Notebooks in an `examples` folder, and give them more explanatory names
Link to Quantopian was broken
Kind reminder to add a license to the Pypi package

Feel free to make any adjustements !
DrPaprikaa

### CODE REVIEW

**Review by Marigold — APPROVED** [review]
Oh man, this is awesome. Thanks for that, I'm extremely bad at writing good readmes

**Comment by Marigold** [comment]
@DrPaprikaa can you merge this yourself or you don't have sufficient permissions?

**Comment by DrPaprikaa** [comment]
I don't think I have the permissions !

**Comment by Marigold** [comment]
@DrPaprikaa added you as a collaborator, you should be able to merge it now

**Comment by DrPaprikaa** [comment]
@Marigold Thanks for the permissions, I merged the PR.
There are still things left to do before closing this issue but I'm afraid you have to it on your side:

1. Create an examples folder and move the notebooks there
2. Rename the notebooks
3. Add a licence to the PyPi package (MIT probably)

I guess that once this is done and the other PRs are merged we are ready for a v0.5 release on PyPi ;)

**Pull request merged**
